// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC6HIIitsPpUsuTEyot-Z4UC5nODDl9GY',
    appId: '1:991979629892:web:cf7f36c8dbebac9e60bb11',
    messagingSenderId: '991979629892',
    projectId: 'sep-hcms-89a9b',
    authDomain: 'sep-hcms-89a9b.firebaseapp.com',
    storageBucket: 'sep-hcms-89a9b.firebasestorage.app',
    measurementId: 'G-PE9308935P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB6W1chMvU_4xq0RE1YKH_QOR4E64-ECM',
    appId: '1:991979629892:android:70e71338d998921960bb11',
    messagingSenderId: '991979629892',
    projectId: 'sep-hcms-89a9b',
    storageBucket: 'sep-hcms-89a9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPCgKB8M6OXM2d5EVn2aC5vo5rgYFNgg8',
    appId: '1:991979629892:ios:5427fbfdd02c0b1c60bb11',
    messagingSenderId: '991979629892',
    projectId: 'sep-hcms-89a9b',
    storageBucket: 'sep-hcms-89a9b.firebasestorage.app',
    iosBundleId: 'com.example.sepHcms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPCgKB8M6OXM2d5EVn2aC5vo5rgYFNgg8',
    appId: '1:991979629892:ios:5427fbfdd02c0b1c60bb11',
    messagingSenderId: '991979629892',
    projectId: 'sep-hcms-89a9b',
    storageBucket: 'sep-hcms-89a9b.firebasestorage.app',
    iosBundleId: 'com.example.sepHcms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC6HIIitsPpUsuTEyot-Z4UC5nODDl9GY',
    appId: '1:991979629892:web:5783b07650b01fde60bb11',
    messagingSenderId: '991979629892',
    projectId: 'sep-hcms-89a9b',
    authDomain: 'sep-hcms-89a9b.firebaseapp.com',
    storageBucket: 'sep-hcms-89a9b.firebasestorage.app',
    measurementId: 'G-1D4E7L8BWD',
  );
}
